### PR TITLE
Adding a Staffing page showing who's teaching where

### PR DESCRIPTION
**Pull request by jiffyclub**
The staffing is generated by hand from another (private) repo and will have
to be updated manually from time to time by someone with access to that repo.
This commit also includes a couple minor style changes in bootcamps/index.html.

This supersedes #336.

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Mar 04, 2013 at 07:07:32AM -0800, Matt Davis wrote:

> - Adding a Staffing page showing who's teaching where.

You might want to leave Greg as the author (or at least credit him in
the commit message.  Team-effort-single-commits can be hard to
properly attribute ;).

**Comment by jiffyclub** [comment]
Done.

**Comment by wking** [comment]
On Mon, Mar 04, 2013 at 07:24:30AM -0800, Matt Davis wrote:

> Done.

It looks good to me now.  I'll let it cook and merge it ~tonight if
nobody beats me to it or finds some terrible flaw ;).

**Comment by jiffyclub** [comment]
I would like to get hold of the script that generates `staffing.html`. It may be possible to pretty up the output HTML and add a [Bootstrap table class](http://twitter.github.com/bootstrap/base-css.html#tables) or two to make the table more readable.

**Pull request merged**
