### PR TITLE
Write program to sync the Google Map and Google Calendar with actual workshop data

### PR DESCRIPTION
**Pull request by wking**
It would be _really_ nice if a single command could update the Google Map to show past and future bootcamps, and simultaneously update the Googel Calendar to show their dates --- doing this by hand is tedious and error-prone. This should also check information against EventBrite (particularly dates and venues).

### CODE REVIEW

**Comment by wking** [comment]
I've attached a pull request with an auto-generated Google Map.

The Google-Calendar portion of this issue was solved by PR #132 [1](https://github.com/swcarpentry/website/pull/132).

@jiffyclub, some of your work is in this commit.  Please review the
commit message and let me know if you think the attribution is
sufficient, or if you want me to split your work out into separate
commits.

Everyone else, please hold off merging until @jiffyclub chimes in.

**Comment by jiffyclub** [comment]
Fine with me, thanks for getting this done.

**Comment by jiffyclub** [comment]
I think the last thing to do here is to set up a Google calendar tracking http://software-carpentry.org/bootcamps.ics and embed it on http://software-carpentry.org/bootcamps/index.html. I could do that but I expect @gvwilson would prefer to be the admin.

That should fully automate the map and calendar.

**Comment by gvwilson** [comment]
On 2012-12-29 8:46 PM, Matt wrote:

> I think the last thing to do here is to set up a Google calendar
> tracking http://software-carpentry.org/bootcamps.ics and embed it on
> http://software-carpentry.org/bootcamps/index.html. I could do that but
> I expect @gvwilson https://github.com/gvwilson would prefer to be the
> admin.
> 
> That should fully automate the map and calendar.

This connects with issue #22 (rationalizing online accounts): I think 
I'd like us to create a new Google account as 'admin', and have our map, 
our calendar, and our analytics all owned by that.

**Pull request merged**
