### PR TITLE
Replacing 'workshop' with 'boot camp' in several places.

### PR DESCRIPTION
**Pull request by gvwilson**
This patch makes terminology more consistent by replacing the word 'workshop' with the word 'boot camp' in most places: most rather than all, because there are places where we say, "A boot camp is a two-day workshop" (or something like that).

### CODE REVIEW

**Comment by jiffyclub** [comment]
Of the six commits attached to this PR, it looks like only 0d182d6 is actually related to any "workshop" -> "boot camp" changes. It would be fairly easy to clean this up by doing an interactive rebase (`git rebase -i 6c7cafa`) and deleting every non-relevant commit, or you could make a new branch from upstream/master and `cherry-pick` 0d182d6.

**Comment by gvwilson** [comment]
On 2013-03-05 10:56 AM, Matt Davis wrote:

> Of the six commits attached to this PR, it looks like only 0d182d6 
> https://github.com/swcarpentry/website/commit/0d182d6 is actually 
> related to any "workshop" -> "boot camp" changes. It would be fairly 
> easy to clean this up by doing an interactive rebase (|git rebase -i 
> 6c7cafa|) and deleting every non-relevant commit, or you could make a 
> new branch from upstream/master and |cherry-pick| 0d182d6 
> https://github.com/swcarpentry/website/commit/0d182d6.
> 
> OK, I ran:

$ git checkout workshop # to get into the branch
$ git rebase -i 0d182d6

I'm now in my editor with the swath of text below.  If I understand 
http://git-scm.com/book/en/Git-Tools-Rewriting-History correctly, what I 
want to do is --- hm, wait a second.  I want to delete all six of the 
commits listed below, since none of them are 0d182d6, but if I erase 
them all, the rebase will be aborted.  Wuzzup?

pick 794a053 Blog post on teaching with ipythonblocks at UW.
pick f0902ea Fixed a tab and mismatched tag.
pick 6c7cafa Slight revision to SWC teaching with ipythonblocks post.
pick be7600f Adding a Staffing page showing who's teaching where.
pick 873c749 Added registration tag and Note
pick 09fcb12 Added page for Soton

# Rebase 0d182d6..cd4dfd8 onto 0d182d6

#

# Commands:

# p, pick = use commit

# r, reword = use commit, but edit the commit message

# e, edit = use commit, but stop for amending

# s, squash = use commit, but meld into previous commit

# f, fixup = like "squash", but discard this commit's log message

# x, exec = run command (the rest of the line) using shell

#

# These lines can be re-ordered; they are executed from top to bottom.

#

# If you remove a line here THAT COMMIT WILL BE LOST.

#

# However, if you remove everything, the rebase will be aborted.

#

# Note that empty commits are commented out

**Comment by jiffyclub** [comment]
I said `git rebase -i 6c7cafa`, not `0d182d6`. You have to rebase onto the commit just before the stuff you want to edit.

**Comment by gvwilson** [comment]
Aaaaahhh.

**Comment by jiffyclub** [comment]
You can update this PR by pushing with the `-f` option: `git push -f origin workshop`.

**Comment by jiffyclub** [comment]
Beautiful!

**Comment by jiffyclub** [comment]
Did you delete the `workshop` branch somehow? That would probably do it. And that's consistent with the other email you sent me.

**Pull request merged**
