### PR TITLE
Small Changes to install instructions

### PR DESCRIPTION
**Pull request by gdevenyi**
Some small cleanups of the language and order of instructions on main page.

Added the requirement for firefox or equivalent on windows since some people actually use IE, which breaks on the etherpad and ipython notebook.

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Apr 16, 2013 at 12:03:58PM -0700, Gabriel Devenyi wrote:

> - Clean up some english and re-order students to install instructions first
- I'm not sure “After following the install instructions” adds much.
  For example, they can use this check list before they go through the
  instructions to see what they need.
- How about “follow” instead of “pick” in “Please pick the
  appropriate…”, to use more standard hyperlink language?
- Missing a “that” in “…page to check everything is…”, or use “…page
  to ensure everything is…”.
- I realize this is a copy-pasted line, but “shell </a>or” should be
  “shell</a> or”.

> - Clarify instructions for windows users
- You have some paragraphs that should be wrapped in `<p>` tags.
- “deprecated”, not “depreciated”.
- “modern, standards compliant”, not “modern standards compliant”.
- I'd prefer:
  
  …  Download and install one of the following:</p>
  
  <ul>
    <li><a href="http://www.fireox.com">Mozilla Firefox</a></li>
    <li><a href="http://www.google.com/chrome">Google Chrome</a></li>
  </ul>
  
  so the list contains only the changing bits of the idea.
- Hah, did you have folks intentionally installing old releases? :p

**Comment by gdevenyi** [comment]
Thanks for the feedback... First time ever submitting something via github, how should I go about integrating these changes?

**Comment by gdevenyi** [comment]
With regards to the "After following the install instructions", I'd be expecting the vast majority of users to have nothing installed, so checking for stuff would be fruitless.

**Comment by wking** [comment]
On Tue, Apr 16, 2013 at 01:13:07PM -0700, Gabriel Devenyi wrote:

> Thanks for the feedback...

No problem :).

> First time ever submitting something via github, how should I go
> about integrating these changes?

Make the changes, then `git commit -a --amend` to squash your new
changes onto your last commit.  Then:

  $ git push --force gdevenyi master 

to update the remote branch you're proposing we merge.  The pull
request will update automatically.

On Tue, Apr 16, 2013 at 01:14:27PM -0700, Gabriel Devenyi wrote:

> With regards to the "After following the install instructions", I'd
> be expecting the vast majority of users to have nothing installed,
> so checking for stuff would be fruitless.

I would expect that a number of them have either Firefox or Chrome
already installed ;).  Also, if they've actually followed the
instructions, there should be nothing to check ;).  It's not really a
big deal though…

**Comment by gdevenyi** [comment]
I tried, but I think I just broke everything.

Git is confusing.

**Comment by gdevenyi** [comment]
Actually, it looks like it worked, but there's an extra commit merging a branch, which didn't change anything. Hopefully this is okay?

**Comment by wking** [comment]
On Tue, Apr 16, 2013 at 02:35:21PM -0700, Gabriel Devenyi wrote:

> I tried, but I think I just broke everything.

If you want to rewind, all the commits that your HEAD used to point to
are recorded in the reflog (git-reflog(1)).

On Tue, Apr 16, 2013 at 02:55:29PM -0700, Gabriel Devenyi wrote:

> Actually, it looks like it worked, but there's an extra commit
> merging a branch, which didn't change anything. Hopefully this is
> okay?

It looks like you made some changes (on top of f6d0e1d instead of
amending to it with `git commit --amend`) giving 06135b3.  Then you
pushed those changes to GitHub.  Then you made more local changes
(this time you did amend them) giving 4451a12.  Then you merged the
earlier 06135b3 into 4451a12 giving 054d7f0, and you pushed _that_ to
GitHub :p.  Since 4451a12 and 054d7f0 are identical:

  $ git diff 4451a12..054d7f0

I'd drop the pointless merge and squash 4451a12 onto f6d0e1d to get
the single commit that `--amend` would have given you in the first
place:

  $ git checkout 4451a12
  $ git reset --soft f6d0e1d^
  $ git commit -m 'Clean up some english and re-order students to install instructions first'
  $ git push --force gdevenyi master

This checks out the state you want (4451a12) then soft resets to the
last commit you want to keep (the parent of your first commit
f6d0e1d).  Then you commit the state you want on top of the commit you
wanted to keep.  Finally, you push your beautiful new single commit to
GitHub.

For other squashing alternatives, see
http://stackoverflow.com/questions/5189560/how-can-i-squash-my-last-x-commits-together-using-git

**Comment by gdevenyi** [comment]
git push --force gdevenyi master

This command reports:
fatal: 'gdevenyi' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

Thoughts?

**Comment by wking** [comment]
On Wed, Apr 17, 2013 at 06:13:05AM -0700, Gabriel Devenyi wrote:

> git push --force gdevenyi master
> 
> This command reports:
> fatal: 'gdevenyi' does not appear to be a git repository
> fatal: The remote end hung up unexpectedly

Use whatever nickname you gave to https://github.com/gdevenyi/website.

  $ git remote -v | grep gdevenyi/website

**Comment by gdevenyi** [comment]
$ git remote -v
origin  https://github.com/gdevenyi/website.git (fetch)
origin          https://github.com/gdevenyi/website.git (push)
upstream    git://github.com/swcarpentry/website.git (fetch)
upstream    git://github.com/swcarpentry/website.git (push)

$git push --force origin master
Everything up-to-date

... nothing changed on github...

I'm tempted to dump my changes to a diff, delete everything and try again...

Not impressed by git at this point.

**Comment by wking** [comment]
On Wed, Apr 17, 2013 at 06:49:02AM -0700, Gabriel Devenyi wrote:

> $ git remote -v
> origin    https://github.com/gdevenyi/website.git (fetch)
> origin            https://github.com/gdevenyi/website.git (push)
> upstream  git://github.com/swcarpentry/website.git (fetch)
> upstream  git://github.com/swcarpentry/website.git (push)
> 
> $git push --force origin master
> Everything up-to-date
> 
> ... nothing changed on github...

Oops, `git checkout 4451a12` means we weren't updating your branch.
Try:

  $ git checkout master
  $ git reset --soft f6d0e1d^ 
  $ git commit -m 'Clean up some english and re-order students to install instructions first' $ git push --force gdevenyi master
  $ git push --force origin master

> I'm tempted to dump my changes to a diff, delete everything and try
> again...

That's what checkout/reset/commit was doing [1](https://github.com/swcarpentry/website/pull/489#issuecomment-16476503), but as I said in that
comment there are other ways to make the squash.  Actually dumping to
diffs is also supported [2](https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#reordering-patch-series).  Use whichever approach you feel most
comfortable with.

> Not impressed by git at this point.

How could Git be improved to help with your current situation?  If you
want more background on other rewriting approaches (or why they are
useful), see [3](https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#cleaning-up-history).

**Comment by gdevenyi** [comment]
Looks like that fixed it. Thanks for your help.

I guess the problem I'm having is that all these commands refer to features/ideas I don't really understand about git yet. Last time I contributed to an OSS project, I was diffing and submitting .patch files...

**Comment by gdevenyi** [comment]
Next up is making a branch and rewriting the instructions to use enthought canopy, but I need to figure out how canopy will interact with msysgit first.

**Comment by wking** [comment]
On Wed, Apr 17, 2013 at 07:16:16AM -0700, Gabriel Devenyi wrote:

> Looks like that fixed it. Thanks for your help.

Oops, one more thing: “shell</a>or” should be “shell</a> or”.  This
time try `git commit -a --amend` the first time ;).

I'll merge after that goes in, unless anyone else comments with other
issues :p.

> I guess the problem I'm having is that all these commands refer to
> features/ideas I don't really understand about git yet. Last time I
> contributed to an OSS project, I was diffing and submitting .patch
> files...

A patch-oriented mindset works pretty well for Git too.  You just need
to know how to tweak and regenerate your patch during the review
phase.  The manual section I linked to previously has details on a
number of possible approaches.

**Comment by gdevenyi** [comment]
So I just pulled from the main SWC repo and now I see an additional commit on this pull request, presumably because I didn't create a branch for my changes. Will this break things?

I guess next time I should be creating a branch with git branch namehere and making the pull request against that right?

**Comment by wking** [comment]
On Wed, Apr 17, 2013 at 07:46:41AM -0700, Gabriel Devenyi wrote:

> So I just pulled from the main SWC repo and now I see an additional
> commit on this pull request, presumably because I didn't create a
> branch for my changes. Will this break things?

Yup.  Use `git reset --hard HEAD^` to unwind the merge.

> I guess next time I should be creating a branch with git branch
> namehere and making the pull request against that right?

Yup again ;).  Until them, you can just:

  $ git checkout upstream/master

to browse around the new stuff.  If you want to develop off the new
stuff, make a new feature branch with:

  $ git checkout -b my-feature upstream/master

Some folks advocate removing their local `master` branch entirely to
avoid the temptation of using it for feature development ;).

**Comment by gdevenyi** [comment]
Success, reverted. I'm going to stop touching things until this is merged now.

**Comment by wking** [comment]
On Wed, Apr 17, 2013 at 10:32:12AM -0700, Gabriel Devenyi wrote:

> Success, reverted. I'm going to stop touching things until this is merged now.

Merged with a243236db4d4fdaade51705ff5b0b04efa34cad6.

**Pull request merged**
