### PR TITLE
Adding drop downs to Boot Camp, Blog, and About menu items

### PR DESCRIPTION
**Pull request by jiffyclub**
Dropdown menu items are:
- Boot Camps
  - About
  - Future Boot Camps
  - Map
  - Calendar
  - Past Boot Camps
- Blog
  - Recent Posts
  - All Posts
- About
  - FAQ
  - Sponsors
  - Team
  - Contributing

### CODE REVIEW

**Comment by jiffyclub** [comment]
This was originally brought up eons ago in #59.

**Comment by gvwilson** [comment]
Nice --- a few thoughts:
1. Click on 'About' to bring up the menu, then click again without moving the mouse: 'About' stays highlighted, even thought we're still on the home page.
2. Given this, 'About' should be right after 'Home'.
3. Yeah, we need to add a menu for 'Lessons'.  It's OK that this isn't dynamically generated --- the 4_0 stuff isn't going to change.  But the first item in the list needs to be 'Index' (or something like that) to go to 4_0/index.html.
Thanks!

**Comment by jiffyclub** [comment]
1. That's the hover. All the menu items highlight when the mouse is over them.
2. Can do.
3. You mean a menu like this?
   - Version Control
   - Python
   - Shell
   - Testing
   - ...
   
   That seems a little overkill given the list at the top of 4_0/index.html.

**Comment by jiffyclub** [comment]
I'm not sure there's anything that can be done about that, it's the clicks that change the open/closed state. Clicking anywhere will collapse the menu.

**Comment by jiffyclub** [comment]
We'd probably have to dig into the Bootstrap JavaScript to change that. I'm not actually writing JS here, just adding classes to things in the menubar. Bootstrap takes care of the rest.

**Comment by jiffyclub** [comment]
I really think the current behaviour is fine (and works exactly like the menubar on my Mac).

**Comment by jiffyclub** [comment]
Yes, but if I move the mouse off the menubar the menus stay open.

**Comment by jiffyclub** [comment]
Cool. Trying to modify the default behaviour of the JS libraries is not something I'm keen to dive into.

**Comment by gvwilson** [comment]
On 2013-01-11 10:16 AM, Matt Davis wrote:

> Cool. Trying to modify the default behaviour of the JS libraries is 
> not something I'm keen to dive into.
> 
> Hm: I googled for 'jquery pulldown menu', and the first example I found 
> does this:

http://www.queness.com/resources/html/dropdownmenu/index.html#

??

**Comment by jiffyclub** [comment]
And Bootstrap dropdowns do this: http://twitter.github.com/bootstrap/javascript.html#dropdowns

I don't think we're going to change this without writing JS, and I'd really rather not. (If someone else wants to...)

**Comment by jiffyclub** [comment]
Cool. If someone really wants to practice their JS and DOM skills in the future we can point them at this.

**Pull request merged**
