### PR TITLE
Blog post about the finances of running boot camps

### PR DESCRIPTION
**Pull request by gvwilson**
Careful review gratefully appreciated.

### CODE REVIEW

**Comment by jiffyclub** [comment]
"enrollment" is misspelled in the image file name.

**Comment by jiffyclub** [comment]
Nevermind, guess "enrollment" is the American spelling.

**Comment by vsbuffalo** [comment]
There's likely a multiplicative effect too, as grad students that took a SC course then teach other grad students and friends what they've learned.

**Comment by kaythaney** [comment]
The notion of charging for a "third instructor who doesn't show up" makes me rather uncomfortable, and I reckon would be rather off-putting to institutions / external partners (remember, these folks exist, too). Having a loose "sponsorship" model for events is a well understood one, at least in my experience, where you make sure you're covering cost but don't line-item every single cost. For a non-profit I work with in the US and UK who run 2-day events with data scientists and charities, we have a sheet where we spec out event cost, in-kind instructor and admin cost, etc., then approach sponsors on a looser basis (for our next event, we have an industry sponsor giving us two quite hefty donations that will pay for much of our operation cost as well for the year). 

I worry that framing it as such comes off as a ghost cost or a "gotcha" sort of practice that you're publicising.

**Comment by npch** [comment]
Do we have strong evidence that charging a deposit or fee for learners would mean that we couldn't get waived room fees? Or only anecdotal?

**Comment by benwaugh** [comment]
I have asked at UCL and they would definitely charge for rooms if we charged a fee. I didn't explicitly ask about a returnable deposit.

**Pull request merged**
