### PR TITLE
Change xml parser

### PR DESCRIPTION
**Pull request by gvwilson**
1. Switch to html5lib and lxml for handling XML (better error handling).
2. Update HTML files (e.g., replace '<td/>' with '<td></td>', turn '<caption>' inside '<figure>' into '<figcaption>') to get past stricter checking.
3. Turn the '&' in the <script src="..."> tag in `bootcamps/index.html` into '&amp;'.

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 10:12:32AM -0800, Greg Wilson wrote:

> - Merge branch 'change-xml-parser' of github.com:gvwilson/website into change-xml-parser

What is going on here?

**Comment by wking** [comment]
Also, the Python-3-incompatible `print >>` syntax is still in
`util.py`.

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 12:19:56PM -0800, Greg Wilson wrote:

> On 2013-01-10 1:35 PM, W. Trevor King wrote:
> 
> > On Thu, Jan 10, 2013 at 10:12:32AM -0800, Greg Wilson wrote:
> > 
> > > - Merge branch 'change-xml-parser' of github.com:gvwilson/website 
> > >   into change-xml-parser
> > 
> > What is going on here?
> > Switching to lxml (better error handling/reporting).

I mean, “what are you trying to accomplish with this merge?”.  The PR
is for the shift to lxml, and partway through the patch series you
merge some stuff from a previous iteration with `master`:

```
$ git log --graph --oneline origin/pr/208
* 498fdbb Fixing the ampersand problem (apparently)
* 98f00a5 Trying to push changes to 3_0 material
* 68a2092 1. Made @jiffyclub's changes to bin/compile.py. 2. Fixed HTML errors reported by LXML/HTML5 parsing. 3. Fixed other bin/* scripts as well (so that HTML5 generation is correct). 4. Still getting one error reported for a <script> tag in bootcamps/index.html that I can't figure out.
* b217a72 Turning off auto-recovery
*   d5b21ff Merge branch 'change-xml-parser' of github.com:gvwilson/website into change-xml-parser
|\  
| * cb5371c Tidying up the switch to LXML
| * 9bc1f92 Switching to lxml
* |   a6f7450 Merge pull request #203 from gvwilson/master
…
```

If you want to incorperate changes that have been made in the master
branch, it would be easier for future developers to figure out why a
change was made if you rebase your whole `change-xml-parser` branch on
top of the current master.  Otherwise, it would be better to leave
your `change-xml-parser` branch separate from master until the final
merge.  I'm not sure which of these approaches is more appropriate in
this situtation.  Was there a particular change in `master` you were
looking to incorporate?

Also, 68a2092 probably needs a blank line after the first in its
commit message, otherwise the whole thing counts as a summary.

**Comment by jiffyclub** [comment]
The history is a little weird but the end result looks fine. At this point do we want to make @gvwilson go through whatever procedure would be necessary to prettify it?

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 04:20:00PM -0800, Matt Davis wrote:

> The history is a little weird but the end result looks fine. At this
> point do we want to make @gvwilson go through whatever procedure
> would be necessary to prettify it?

It's not to bad.  I don't think there were any semantic changes merged
from master, so:

```
$ git checkout change-xml-parser
$ git rebase a6f74501
$ git push --force gvwilson change-xml-parser
```

is an easy way to dump the odd merge.

**Comment by wking** [comment]
On Fri, Jan 11, 2013 at 03:21:00AM -0800, Greg Wilson wrote:

> On 2013-01-10 7:29 PM, W. Trevor King wrote:
> 
> > It's not to bad. I don't think there were any semantic changes merged
> > from master, so:
> > 
> > $ git checkout change-xml-parser
> > $ git rebase a6f74501
> > $ git push --force gvwilson change-xml-parser
> > 
> > is an easy way to dump the odd merge.
> 
> OK, I've made the `print >> sys.stderr` => `sys.stderr.write` change and 
> pushed to change-xml-parser in GitHub; time to rebase.  I'm guessing 
> that the `git rebase a6f74501` command will --- hm, OK, I'm not sure.

`rebase` in general takes your current `HEAD` and reconstructs it as
if it was based on the mentioned commit.

> That's clearly the ID of a node in the change graph, but none of the 
> examples in 'man git' show that syntax: they all use branch names.

a6f74501 is the commit in the `master` branch which you used to create
the dud merge in your `change-xml-parser` branch.  However, `master`
has moved on in the meantime.  You can find the most recent shared
commit with `merge-base`:

  $ git merge-base change-xml-parser origin/master
  a6f745015e731c607ba07dfa5143e4c5fb4bd299

> And why am I pushing with --force?

Rebasing removes the old commits in this branch and replaces them with
new ones.  The diffs don't change, but the parent references and
commit timestamps do, so the commit SHA1s change.  This means that the
new `change-xml-parser` tip will not be a descendent of the old tip.
`--force` tells `git push`, “I realize the new reference I'm pushing
is not a descendant of the current reference, go ahead and clobber the
old reference”.  If you do this for a branch that other people have
worked on (e.g. `master`), you can have problems (see the RECOVERING
FROM UPSTREAM REBASE section of `git rebase --help), but it's fairly
common practice to reroll feature branches a few time to polish up
their logic and clarity.

**Pull request merged**
