### PR TITLE
bootcamps/index.html: Add a 'calendar' ID to the calendar <p>

### PR DESCRIPTION
**Pull request by wking**
This allows more direct linking, e.g. from the root index.html.

### CODE REVIEW

**Comment by jiffyclub** [comment]
I broke this merging #171. Do you want to rebase, or one of us can just make these changes directly.

**Comment by wking** [comment]
On Wed, Jan 02, 2013 at 07:35:07AM -0800, Matt wrote:

> I broke this merging #171. Do you want to rebase, or …

I just pushed the rebased branch.

**Comment by jiffyclub** [comment]
Is `blog/index-date.html` supposed to be part of this?

**Comment by wking** [comment]
On Wed, Jan 02, 2013 at 08:06:55AM -0800, Matt wrote:

> Is `blog/index-date.html` supposed to be part of this?

Oops.  Gone now ;).

**Pull request merged**
