### PR TITLE
Adding a bootcamp page for the CAMH bootcamp

### PR DESCRIPTION
**Pull request by pipitone**

### CODE REVIEW

**Comment by pipitone** [comment]
I didn't know if it was appropriate to also include the assessment in 5.1 (or exactly how to do that, or exactly how people would take and grade their answers) so I just left it out for now.

**Comment by gvwilson** [comment]
On 2012-12-20 4:55 PM, pipitone wrote:

> I didn't know if it was appropriate to also include the assessment in
> 5.1 (or exactly how to do that, or exactly how people would take and
> grade their answers) so I just left it out for now.

I don't understand...?

**Comment by pipitone** [comment]
I'm saying that I didn't include a link to the pre-assignment survey.

**Comment by gvwilson** [comment]
On 2012-12-20 5:06 PM, pipitone wrote:

> I'm saying that I didn't include a link to the pre-assignment survey.

Right, because we need to create it on SurveyMonkey or something like 
that once you approve the questions...

**Pull request merged**
