### PR TITLE
Adding a 'staffing' page.

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Mar 03, 2013 at 04:58:57AM -0800, Greg Wilson wrote:

> - 1. Adding 'bootcamps/staffing.html' page (generated from another repo).

Another long commit message summary ;).

> - Merge branch 'bootcamps'

The commit message doesn't list any conflicts resolved by this merge.
Is there a particular reason you made the merge?  As it stands, the
“Merge Pull Request” button will probably lead to something like:

```
* XXXXXXX (master) Merge pull request #334 from gvwilson/master
|\
| * 94c6663 (origin/pr/334) Merge branch 'bootcamps'
|/|
* | 8218f76  Merge remote-tracking branch 'pipitone/mailing_list_signup'
| * 0a8a697 1. Adding 'bootcamps/staffing.html' page …
…
```

Which seems unnecessarily convoluted ;).

**Comment by jiffyclub** [comment]
@gvwilson works in `master` a lot so he ends up with a lot of these merge commits... Greg, one of the beauties of working in branches is that you don't have worry about upstream changes unless it ends up that your branch can't be cleanly merged because of conflicts.

**Comment by wking** [comment]
On Sun, Mar 03, 2013 at 07:10:52AM -0800, Greg Wilson wrote:

> Understood; mostly I wanted someone to check it over.

It's easier to check a linear history without merges, because then we
don't have to verify that nothing odd happened during the merge
itself.  It looks like the only substantive changes since #330 are in
0a8a697.  Here are my thoughts:
- I like the links to the staffing page.
- I also like the `</li>` → `</p>` typo fix.
- I'm agnostic on the code of conduct emphasis.
- I assume the staffing.html changes are just a rerun of the same
  script on a more up to date database, in which case they're probably
  fine.  I'd still like to have the script committed though ;).
- I think that each change enumerated in the 0a8a697 commit message
  should be rerolled as a separate commit (although I've been
  overruled before, e.g. 961691d) :p.

**Comment by jiffyclub** [comment]
I didn't realize the tab and mismatched tag fixes were in this PR, I just fixed those in f0902ea6ad2cca761604f2ca4578388226ff1969. You'll have to rebase this PR before it can be merged.

**Comment by jiffyclub** [comment]
Otherwise this looks fine.

**Pull request closed without merging**
