### PR TITLE
Feedback on setup/index.html and setup/tests.html please?

### PR DESCRIPTION
**Pull request by caitsydney**
See my recent commit details for specific questions I have:
https://github.com/picken19/website/commit/6709732ef5fee15e67461382b0bcbe951bf427ea

### CODE REVIEW

**Comment by jiffyclub** [comment]
I'm not a fan of the box. I'd suggest just trying to match styles with the rest of the site so that we keep things consistent. We'll probably keep iterating on the site design and do everything at once.

Are we really suggesting people use nano, vim, and emacs? These are the setup instructions I put together for my boot camps in October: http://swcarpentry.github.com/2012-10-caltech/#install

**Comment by gvwilson** [comment]
> I'm not a fan of the box. I'd suggest just trying to match styles with
> the rest of the site so that we keep things consistent. We'll probably
> keep iterating on the site design and do everything at once.

I like the grid approach --- it's a lot easier for both instructors and 
learners to see what's there.  Matt, can you suggest a layout that would 
be equally easy to navigate?

> Are we really suggesting people use nano, vim, and emacs?

Let's get an easy-to-read format first (even I have lost track of what's 
in the existing setup instructions), and then we can vote and arm 
wrestle over specifics --- in particular, I think we need to decide what 
we're doing about Windows before we do anything else :-(

**Comment by jiffyclub** [comment]
We could make some columns similar to what I did on this page: http://swcarpentry.github.com/2012-10-caltech/#install. Though three columns might get a bit tight.

We could also make a grid of links/buttons that either:
- link to an appropriate page
- pop open a dialog or tooltip with additional info

**Comment by gvwilson** [comment]
Please no popups (dialogs and tooltips) - makes the site harder for the 
physically/visually disabled to work with.

**Comment by caitsydney** [comment]
I can add the self-check scripts (#38, #39, #40) as an option in the tests.html page, if everyone is okay with that? I think then instructors could add their own scripts - I believe Fernando had some from his workshop - as they write them. The scripts seem like they may be comprehensive. Since we are using them, would we still need the specific testing instructions for how an attendee manually tests each thing they installed?

I've just been building the install info based on what was in the original page - I'll have a better idea of exactly what needs to go there after Wednesday, I'm hoping.

@gvwilson, I didn't know what to call the troubleshooting page. Will rename it. 

@jiffyclub, I really like the columns. I'll look at the code for it and see about doing something similar. I just wanted a way to divide the page more clearly for readability. A lot of info has to go on each page. I like your "bash," "git," etc. title boxes. That could work well.

Everyone - I'm going to need some sort of consensus about what people will need to install. Obviously people can use any text editor they prefer, but which one(s) should the website recommend? Same question for version control - do we need install instructions/use instructions for git/github, svn, BitBucket, and Mercurial? Something to talk about on Wednesday too, I think.

If we _do_ need all of those VC install/test instructions, would it make sense to have subpages specific to each type? The tests.html page is quickly getting unwieldy in length.  

setup
    >index.html
    >troubleshooting.html
    >install/
           >versioncontrol.html
           >texteditor.html
           >python.html
     >testing/    ---   has a toc linking to each type of software you will need
           >versioncontrol_test.html    -----   has a toc; attendees only focus on the vc they have been assigned by host
           >texteditor_test.html
           >python_test.html
           >scripts.html

**Comment by jiffyclub** [comment]
The columns on that page are made using Bootstrap's grid system, docs here: http://twitter.github.com/bootstrap/scaffolding.html#fluidGridSystem

**Comment by jiffyclub** [comment]
Some setup instructions will definitely be boot camp dependent. Not every boot camp has SQL, some of us do Mercurial, some of us do git...we were trying to come with a good way to make this very modular so instructors could put together just the instructions that applied to their boot camp.

**Pull request closed without merging**
