### PR TITLE
Create "check my machine" script for Linux

### PR DESCRIPTION
**Pull request by wking**
Write a small script that people can download from our web site and run on their machine that will tell them if everything they need for a boot camp has been installed correctly.  See https://github.com/drj11/prace/blob/master/gotit for a starting point.

### CODE REVIEW

**Comment by wking** [comment]
I'll claim this (unless someone else is already working on it?)

**Comment by gvwilson** [comment]
On 2012-12-29 3:43 PM, W. Trevor King wrote:

> I'll claim this (unless someone else is already working on it?)

It's yours.  Cait Pickens is driving the editing/layout of the setup 
instructions, so please sync with her about content.
Cheers,
G

**Comment by wking** [comment]
I'm pushing a WIP.  @picken19, how does it look to you?

@khinsen and @fperez, I stuck your scripts in at the bottom of the
version control history for my branch.  Let me know if you want to
tweak commit messages, or if you can point me towards additional
history that I should graft on underneath before this gets merged into
the website repository.

**Comment by khinsen** [comment]
@wking All is fine with me. There's no further history worth recording.

**Comment by wking** [comment]
If workshop leads are supposed to make per-workshop alteration
(e.g. selecting active dependencies), perhaps this should live in
boot-camps instead of website?

**Comment by gvwilson** [comment]
Agreed --- can you please update tickets and/or move files?
- G

**Comment by wking** [comment]
I'm closing this PR.  Future feedback should go in swcarpentry/boot-camps#12, which currently has a fairly complete implementation.

**Pull request closed without merging**
