### PR TITLE
Blog post about UBC boot camp

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by pipitone** [comment]
He who merges his own pull requests...

**Comment by jiffyclub** [comment]
I don't really mind if Greg pushes stuff in without review (he's the boss), but it's kind of silly to make a PR when you don't plan to have people review it.

**Comment by jiffyclub** [comment]
Yes, if you're planning to immediately merge it anyway.

That said, it would be better if you made the post in a branch and then made a PR that you left open long enough for someone to proof it. That might save you from commits like this one f8aab4e4bf9e2827501c17906e93f20b2f375759.

**Pull request merged**
