### PR TITLE
Adding a way to contact us to request a boot camp

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Mar 12, 2013 at 05:45:07PM -0700, Greg Wilson wrote:

> - Adding a way to contact us to request a boot camp

Maybe "email us" instead of "send us email"?

**Comment by jiffyclub** [comment]
Or "send us _an_ email"?

**Comment by wking** [comment]
On Wed, Mar 13, 2013 at 04:00:41AM -0700, Greg Wilson wrote:

> On 2013-03-12 11:13 PM, Matt Davis wrote:
> 
> > Or "send us /an/ email"?
> > 
> > Emailest us, oh thou hopeful aspirant.

Verily, and whosoever sendest, in their wisdom, electronic
correspondence in the common mode, shall be granted, insofar as it
stands within our power, several learned persons, who, descending with
rapidity on the agreed upon locality, will inspire a receptive
populace to sally forth into a world of sane software development.

;)

**Comment by gvwilson** [comment]
Wording changed.

**Pull request merged**
