### PR TITLE
Adding a page that displays upcoming boot camps' staffing

### PR DESCRIPTION
**Pull request by gvwilson**
Our database of who's teaching what, when, is stored in a separate (private) 'admin' repo, since it includes things like personal email addresses.  There's a script in that repo that generates a static HTML page 'bootcamps/staffing.html', which we will check into this repo periodically.

### CODE REVIEW

**Comment by wking** [comment]
On Fri, Mar 01, 2013 at 12:39:09PM -0800, Greg Wilson wrote:

> Our database of who's teaching what, when, is stored in a separate
> (private) 'admin' repo, since it includes things like personal email
> addresses.  There's a script in that repo that generates a static
> HTML page 'bootcamps/staffing.html', which we will check into this
> repo periodically.

Can you commit the script and an SQL dump of this database with some
dummy data (in assets?)?  It would be nice to limit the secret keeping
to the sensitive data (and have a public script, schema, etc.).

**Comment by jiffyclub** [comment]
Do you also want to add a link to this from somewhere?

**Comment by jiffyclub** [comment]
What's its purpose if people can't browse to it?

**Comment by jiffyclub** [comment]
The Bootcamps menu drop down and/or somewhere on `bootcamps/index.html`.

**Pull request closed without merging**
