### PR TITLE
Update UW April bootcamp webpage

### PR DESCRIPTION
**Pull request by lmichael107**
Updated location, customized wording, added registration link

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Mar 21, 2013 at 08:24:31AM -0700, lmichael107 wrote:

> - Customized wording; Added registration, specific location
> - Revert &quot;For 2013-04-wisc.html: Customized wording; Added registration, specific location&quot;
> - Fixing unintended revert.

This history looks unnecessarily complicated ;).  If everything you
want is in b9e4294, you should be able to fix the PR with:

  $ git checkout master
  $ git reset --hard b9e4294
  $ git push -f lmichael107 master

**Comment by lmichael107** [comment]
I'm just learning git (with help from Paul Wilson). Sorry about the complicated history, but I think this is the best we can do for now. We've rebased per @gvwilson request, and it should be ready to pull now.
-Lauren

**Comment by wking** [comment]
On Thu, Mar 21, 2013 at 09:26:05AM -0700, lmichael107 wrote:

> Sorry about the complicated history, but I think this is the best we
> can do for now.

No problem.  I would expect that devs here enjoy teaching this sort of
thing, so you're in good hands ;).

> We've rebased per @gvwilson request, and it should be ready to pull
> now.

Looks good to me.  I'll merge in a few hours if we don't get further
feedback from someone else…

**Comment by gvwilson** [comment]
Looks good to me too, so I'll merge right away and push to the web site.

**Comment by wking** [comment]
On Thu, Mar 21, 2013 at 09:43:35AM -0700, Greg Wilson wrote:

> Looks good to me too, so I'll merge right away and push to the web site.

Works for me.

**Pull request merged**
