### PR TITLE
Small changes to LO

### PR DESCRIPTION
**Pull request by caitsydney**

### CODE REVIEW

**Comment by wking** [comment]
Looks good to me, although I might just eliminate `Recognize redundant
information` entirly, since it seems to overlap with the following
`Reorganize database tables to eliminate redundancy`.

**Comment by wking** [comment]
I just realized that this PR is pulling in some of Greg's
instructors-guide branch too.  Comments on those commits:

On Mon, Jan 14, 2013 at 04:29:11PM -0800, Caitlyn wrote:

> - Starting to revise web material

There seem to be a number of tab-indented lines in here.

Also was/is inconsistency in “SGML was very complex…”

I'm not wild about “they allow us to explicitly specify the "what"
that we infer so easily for computers' benefit.”  I think I like the
previous version of this sentence better.

I'd wrap the ampersand reference in <code> tags too: “an escape
sequence is an ampersand <code>&amp;</code>”.

You're missing a “be” in “The hyperlink element is called
<code>a</code> because it can also used”.

> - Adding some challenges

There seem to be a number of tab-indented lines in here.

> - Converting database chapter to learning goals

There seem to be a number of tab-indented lines in here.

**Comment by jiffyclub** [comment]
With #229 @gvwilson has merged his above commits into the master branch. You'll need to rebase on his changes or, since your changes are pretty small, just make a new branch from master and reprise them.

**Comment by jiffyclub** [comment]
Alright, closing this, then.

**Pull request closed without merging**
