### PR TITLE
Credit website authors in an auto-generated AUTHORS file.

### PR DESCRIPTION
**Pull request by wking**
The initial version of this pull request is a work in progress.  Don't
merge yet!

Motivation: as I mentioned in #63, I've written an
`update-copyright.py` script [1](http://pypi.python.org/pypi/update-copyright/) to automatically keep track of boring
copyright/license details.  The script reads the VCS history to
generate a list of authors who have contributed to the repository (it
can also automatically update per-file copyright blurbs, but I'm not
using that here yet).  Because SWC doesn't require copyright
assignment, something along these lines (even if it's just maintaining
the `AUTHORS` file by had) is probably required, or we'll be violating
the MIT/CC BY license under which we accept patches from contributors.

Drawbacks to using my script over updating `AUTHORS` by hand:
- Another dependency!  Although if update-copyright becomes to
  burdensome it is easy to switch to manual maintenance later.  Just
  remove `.update-copyright.conf` from version control.

Benefits to using my script:
- You don't have to remember to bump the `AUTHORS` file ever again.
  Just run `update-copyright.py` before tagging a release (or once
  every few months).

Issues to be resolved:
- I don't have names for a goodly number of
  http://svn.software-carpentry.org contributors, and I don't have any
  information at all about where the pre-2009 content came from (it
  was in http://swc.scipy.org/svn/All, but then lost during the move
  to http://svn.software-carpentry.org).

This PR, if accepted, should probably be rebased on top of #177 to
avoid double-counting contributors with inconsistent Git author IDs.

```
 http://blog.tremily.us/posts/update-copyright/
```

### CODE REVIEW

**Comment by gvwilson** [comment]
On 2013-01-01 5:31 PM, W. Trevor King wrote:

> Motivation: as I mentioned in #63 
> https://github.com/swcarpentry/website/issues/63, I've written an
> 
> |update-copyright.py| script 1 
> http://pypi.python.org/pypi/update-copyright/ to automatically keep 
> track of boring
> copyright/license details.

Even in my wildest dreams, we won't ever have enough contributors to 
need to automate this task :-)  Fixing #161 (which will require an 
extension to `bin/compile.py`) would be more useful...

**Comment by wking** [comment]
On Tue, Jan 01, 2013 at 04:10:43PM -0800, Greg Wilson wrote:

> Even in my wildest dreams, we won't ever have enough contributors to 
> need to automate this task :-)

Probably not.  Still, SWC has been around for a number of years, and
there is no AUTHORS file yet ;).  And if you have one that is
automatically maintained, new contributors don't have to bump you for
inclusion in it ;).

**Comment by gvwilson** [comment]
Over-engineering.

**Comment by wking** [comment]
On Tue, Jan 01, 2013 at 07:37:26PM -0500, W. Trevor King wrote:

> Still, SWC has been around for a number of years, and there is no
> AUTHORS file yet ;).

The `CONTRIBUTING.md` file that rode in with #203 addresses author
crediting by referring people to
http://software-carpentry.org/badges/creator.html.  That's enough for
me, although there are a number of folks in the VCS history that don't
have creator badges (yet?).

**Comment by jiffyclub** [comment]
Does that mean we're going to conflate creating teaching material and hacking on support stuff?

**Pull request closed without merging**
