### PR TITLE
Boot camps missing from calendar page

### PR DESCRIPTION
**Pull request by jiffyclub**
1. Go to http://software-carpentry.org/bootcamps/.
2. Scroll down to the calendar.
3. The list shows boot camps in May at Stanford, LBNL, UC Berkeley, and UC Davis (screenshot 1).
4. The Google Calendar _doesn't_ show these boot camps when you page forward to May (screenshot 2).
   Screen Shot 2013-02-19 at 11 17 05 AM
   Screen Shot 2013-02-19 at 11 17 45 AM

### CODE REVIEW

**Comment by amyrhoda** [comment]
Hm. This seems to be broken again. The Wisconsin and Maryland camps, among others, are missing from the calendar on the website (although they show up in my iCal where I am subscribed to the calendar feed). I tried removing the spaces in the latlng value in a few recent boot camp pages (https://github.com/swcarpentry/website/pull/517) but it didn't seem to work, at least not on my local build.

**Comment by jiffyclub** [comment]
I merged #517, I think the calendar should be fixed in the next website rebuild whenever that happens.

I still think we should just strip white space in the `.ics` creation code.

**Comment by jiffyclub** [comment]
You're about two hours late, this _is_ a pull request. :wink:

**Pull request merged**
