### PR TITLE
Expanding template variables in blog post excerpts in blog/index.html

### PR DESCRIPTION
**Pull request by gvwilson**
Inspired by @wking's approach, rendering the {% content %} block of selected blog posts in place in blog/index.html.

### CODE REVIEW

**Comment by wking** [comment]
It took me a while to test this (partly due to #168), but I think #159
is still a better choice here.  For example, it is unclear how future
blog posts using the `youtube` macro will have that expanded under
this fix.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 07:22:36AM -0800, Greg Wilson wrote:

> I don't understand: calls to the 'youtube' macro seem to be 
> self-contained (title, YouTube stub, time), so why can't they be 
> expanded safely with the approach in #166?

Because the `youtube` macro is defined in `_base.html`, which your
on-the-fly `excerpt()` template doesn't use for rendering.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 09:33:35AM -0800, Greg Wilson wrote:

> On 2013-01-03 10:39 AM, W. Trevor King wrote:
> 
> > Because the `youtube` macro is defined in `_base.html`, which your
> > on-the-fly `excerpt()` template doesn't use for rendering.
> 
> Well caught :-)  I'll fix...

Or you could use my PR, where it is fixed ;).

**Comment by gvwilson** [comment]
On 2013-01-03 10:39 AM, W. Trevor King wrote:

> On Thu, Jan 03, 2013 at 07:22:36AM -0800, Greg Wilson wrote:
> 
> > I don't understand: calls to the 'youtube' macro seem to be
> > self-contained (title, YouTube stub, time), so why can't they be
> > expanded safely with the approach in #166?
> 
> Because the `youtube` macro is defined in `_base.html`, which your
> on-the-fly `excerpt()` template doesn't use for rendering.
> OK, after talking with @pipitone, and re-reading @wking's fix, here's an 
> alternative patch:

https://github.com/gvwilson/website/commit/087edfc03cc814a4d455cdc5f18a906f65c84f7d

It:
- only double-compiles the bodies of the handful of blog posts that are 
  appearing in the feed.xml and blog/index.html docs
- separates de-HTMLification from content compilation
- strips tags out of the 'description' (excerpt), which @pipitone tells 
  me is required

Thx,
G

**Comment by wking** [comment]
On Mon, Jan 07, 2013 at 12:29:20PM -0800, Greg Wilson wrote:

> On 2013-01-03 10:39 AM, W. Trevor King wrote:
> 
> > On Thu, Jan 03, 2013 at 07:22:36AM -0800, Greg Wilson wrote:
> > 
> > > I don't understand: calls to the 'youtube' macro seem to be
> > > self-contained (title, YouTube stub, time), so why can't they be
> > > expanded safely with the approach in #166?
> > 
> > Because the `youtube` macro is defined in `_base.html`, which your
> > on-the-fly `excerpt()` template doesn't use for rendering.
> > OK, after talking with @pipitone, and re-reading @wking's fix, here's an 
> > alternative patch:
> 
> https://github.com/gvwilson/website/commit/087edfc03cc814a4d455cdc5f18a906f65c84f7d

I don't like hardcoding the `youtube` import in compile.py.  See my PR
for an example of including content-generating macros in a separate
file.  This makes it easy for people who only speak Jinja to add new
macros, without having to root around inside compile.py.

> - only double-compiles the bodies of the handful of blog posts that are 
>   appearing in the feed.xml and blog/index.html docs
> - separates de-HTMLification from content compilation
> - strips tags out of the 'description' (excerpt), which @pipitone tells 
>   me is required

These are all good ideas.

**Comment by gvwilson** [comment]
On 2013-01-07 9:03 PM, W. Trevor King wrote:

> On Mon, Jan 07, 2013 at 12:29:20PM -0800, Greg Wilson wrote:
> 
> > On 2013-01-03 10:39 AM, W. Trevor King wrote:
> > 
> > > On Thu, Jan 03, 2013 at 07:22:36AM -0800, Greg Wilson wrote:
> > > 
> > > > I don't understand: calls to the 'youtube' macro seem to be
> > > > self-contained (title, YouTube stub, time), so why can't they be
> > > > expanded safely with the approach in #166?
> > > 
> > > Because the `youtube` macro is defined in `_base.html`, which your
> > > on-the-fly `excerpt()` template doesn't use for rendering.
> > > OK, after talking with @pipitone, and re-reading @wking's fix, 
> > > here's an
> > > alternative patch:
> > 
> > https://github.com/gvwilson/website/commit/087edfc03cc814a4d455cdc5f18a906f65c84f7d
> 
> I don't like hardcoding the `youtube` import in compile.py. See my PR
> for an example of including content-generating macros in a separate
> file. This makes it easy for people who only speak Jinja to add new
> macros, without having to root around inside compile.py.
> b4e60c4 uses:

```
 content = 
```

'\n'.join("{% from '_content_macros.html' import youtube %}", self.content])

while my patch does:

```
 temp = "{% from '_content_macros.html' import youtube %}\n" + 
```

self.content

Is this OK now?
G

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 12:13:52PM -0800, Greg Wilson wrote:

> On 2013-01-07 9:03 PM, W. Trevor King wrote:
> 
> > https://github.com/gvwilson/website/commit/087edfc03cc814a4d455cdc5f18a906f65c84f7d
> > 
> > I don't like hardcoding the `youtube` import in compile.py. See my PR
> > for an example of including content-generating macros in a separate
> > file. This makes it easy for people who only speak Jinja to add new
> > macros, without having to root around inside compile.py.
> > b4e60c4 uses:
> 
> ```
>  content = 
> ```
> 
> '\n'.join("{% from '_content_macros.html' import youtube %}", self.content])
> 
> while my patch does:
> 
> ```
>  temp = "{% from '_content_macros.html' import youtube %}\n" + 
> ```
> 
> self.content

Oops, looks like I'm guilty too ;).  I think it would be better to use:

```
{% import '_content_macros.html' as macros %}
```

in both `_base.html` and `compile.py`, and explicitly namespace in the
blog posts:

```
{{ macros.youtube(…) }}
```

If you want to skip this renaming, I'm ok with the current status of
087edfc0.

**Comment by gvwilson** [comment]
> Oops, looks like I'm guilty too ;). I think it would be better to use:
> 
> {% import '_content_macros.html' as macros %}
> 
> in both `_base.html` and `compile.py`, and explicitly namespace in the
> blog posts:
> 
> {{ macros.youtube(…) }}
> If we change `_base.html`, we have to change 130 other files (most in 
> 4_0, some in blog). Since we're planning to scrap this all when we move 
> to Pelican, I vote for taking the patch as-is.

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 06:38:03PM -0800, Greg Wilson wrote:

> > Oops, looks like I'm guilty too ;). I think it would be better to use:
> > 
> > {% import '_content_macros.html' as macros %}
> > 
> > in both `_base.html` and `compile.py`, and explicitly namespace in the
> > blog posts:
> > 
> > {{ macros.youtube(…) }}
> 
> If we change `_base.html`, we have to change 130 other files (most in 
> 4_0, some in blog). Since we're planning to scrap this all when we move 
> to Pelican, I vote for taking the patch as-is.

I don't mind waiting until the Pelican changes go in, but I expect
that the change from `youtube` to `macros.youtube` will not conflict
with any Pelican-related changes.

**Comment by gvwilson** [comment]
> I don't mind waiting until the Pelican changes go in, but I expect
> that the change from `youtube` to `macros.youtube` will not conflict
> with any Pelican-related changes.
> What're the odds something in the Pelican changes will make this all 
> redundant anyway?

**Comment by wking** [comment]
On Thu, Jan 10, 2013 at 06:53:18PM -0800, Greg Wilson wrote:

> > I don't mind waiting until the Pelican changes go in, but I expect
> > that the change from `youtube` to `macros.youtube` will not conflict
> > with any Pelican-related changes.
> 
> What're the odds something in the Pelican changes will make this all 
> redundant anyway?

I think Pelican is unlikely to bundle a link-to-youtube Jinja macro in
the near future, although they do have a youtube directive for ReST.
The compile.py stuff is likely to be irrelevant after the Pelican
migration.

How long it will take me to convert the site to Pelican on my own is
still an open question.  It takes a while to build the site (mostly
due to slow disk speed for my USB 2 root drive ;), so the
compile/check/fix cycle is slow.  I might be done in another week?

**Pull request merged**
