### PR TITLE
Adding page for UMB (U Maryland Baltimore) camp

### PR DESCRIPTION
**Pull request by amyrhoda**

### CODE REVIEW

**Comment by embray** [comment]
Should this be UMBC?  That's the acronym usually used for, well, UMBC.

**Comment by amyrhoda** [comment]
No, you're thinking of University of Maryland, Baltimore County (often referred to as UMBC), which is, according to Wikipedia, not to be confused with University of Maryland, Baltimore (referred to as UMB). Wikipedia's exhortations not to be confused do not seem to be working. I'm 99.9% sure that this boot camp is, in fact, being held at UMB, not UMBC. I only hope the people attending know how to get there.

**Comment by embray** [comment]
Ack, my apologies then.  I didn't even know there _was_ a separate UMB.

**Comment by amyrhoda** [comment]
Believe me, this has caused me quite a lot of confusing and consternation over the last few days! I'm actually glad to know it's not just me. :)

**Pull request merged**
