### PR TITLE
Colour, font, and small layout changes to improve readability

### PR DESCRIPTION
**Pull request by pipitone**
- Base text font face changed for readability
- Changed navbar colors: text is white for higher contrast
- Text and heading colour changed to different greys for contrast
- Align blog text with heading

### CODE REVIEW

**Comment by pipitone** [comment]
Check out http://dev.software-carpentry.org to see this in action (for now). Or, look at this: 
image

**Comment by gvwilson** [comment]
Still wouldn't mind if the text was blacker, but maybe that's just my eyes...

**Comment by pipitone** [comment]
Now with darker text! (Updated on dev.. ), also here: 
image

**Comment by gvwilson** [comment]
+1 from me. @jiffyclub?

**Comment by jiffyclub** [comment]
I liked the headers the lighter grey. It was just the body text I wanted darker. Having the headers lighter shades makes for nice delineation without smashing large, black text into your eyes.

**Comment by pipitone** [comment]
PRs welcome.. :-)

**Comment by jiffyclub** [comment]
I think prefer the navbar the way it was. Having all the titles white seems a bit overdone and the dark-background highlighting isn't particularly effective against the dark bar. I'd suggest just leaving it as it was, though it might be worthwhile to bump the font size up a smidgen.

**Comment by gvwilson** [comment]
And then we'll aaaaaaall promise to stop futzing with the web site and get back to creating content, right? :-)  Cuz, you know, if _I_ have to...

**Comment by jiffyclub** [comment]
Yes, to be honest I have so much to do to prep for Seattle I'd rather not worry about this now. My suggestions:
- go with Bootstrap default for the body text (`#333333` I think)
- set the header color to `#515151` or whatever you had it at first
- leave the navbar links as they were

I'd also like to make it so that on the front page the paragraph blocks are organized into rows (with headers matching on the left and right), think it looks cleaner and easier on the eyes. But, an easy fix for another time.

**Comment by pipitone** [comment]
Eh. Forget it. I retract my PR.  :-)

**Comment by jiffyclub** [comment]
Well, the font change is definitely nice, I'd like to see at least that go in.

**Comment by jiffyclub** [comment]
Also the re-arrangement of the headers.

**Comment by pipitone** [comment]
@jiffyclub Okay, the latest commit has just the font, heading changes, and text colour (but both are set to `#333`).

To be honest, I think something has to be done about the current navbar highlighting because it's worse than black on blue... it's blue on blue. I also find the grey font difficult to read on the dark blue background. But hey, that can be for another PR... ;-)

**Pull request merged**
