### PR TITLE
Menu bar on web site fails on Internet Explorer

### PR DESCRIPTION
**Pull request by embray**
A user reports:

I was checking out the lessons, and when you do the top menu bar stops functioning completely. You cannot select anything to see sub folders and whatnot. I have attached a screenshot.
I am using the latest version of internet explorer to view the site.

See @gvwilson for user's contact info.

site bug

### CODE REVIEW

**Comment by gvwilson** [comment]
@iguananaut any progress on this one?

**Comment by embray** [comment]
Okay, I figured out what the problem is.  I would attach a pull request, but I don't understand all the details of how these web pages are compiled so I won't touch it just yet...

The problem is with those `<!-- pageclass: foo -->` comments on some of the template pages that apparently serve some purpose for `compile.py`.

On the Lesson pages and on the Blog pages the templates are such that those comments, such as `<!-- pageclass: LessonPage -->`, appear before `<!DOCTYPE html>` declaration.  This confuses IE, and when IE gets confused it gets angry and converts the entire page to an HTML4 Transitional compatibility mode where nothing works.

So you just need to fix those templates to not do that.

**Comment by gvwilson** [comment]
Ouch.  OK, I can do that.
Greg

**Comment by embray** [comment]
I just attached a PR.

**Comment by gvwilson** [comment]
The fix was simple; the Git is not (submodules). Here's what I've done:
1. In my clone of the 4_0 repository (gvwilson/4_0), I've created a 
'pageclass' branch and committed small edits to _lesson.html and 
_topic.html.
2. In my clone of the website repository (gvwilson/website), I've 
created a 'pageclass' branch and committed small edits to 
blog/_blog.html, blog/index.html, and bootcamps/_bootcamp.html
3. When I'm on the 'pageclass' branch in my website clone on my Mac, and 
run 'git status', I get:

# modified:   4_0 (new commits)
1. Before I type anything else, I'm going to ask a grownup to tell me 
   what my next step should be: what do I do in 'website' to make it happy 
   with the current state of the '4_0' submodule?
2. Do I wait to resolve that before issuing pull requests for 4_0 and 
   website on GitHub?
   Thanks,
   Greg

**Comment by embray** [comment]
Well I don't know about the submodule stuff, but you could just merge this PR :)

**Comment by jiffyclub** [comment]
@gvwilson, start by getting your 4_0 changes into the swcarpentry/lessons_4_0 repo (via a PR or a push).

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 07:22:05AM -0800, Erik Bray wrote:

> Well I don't know about the submodule stuff, but you could just
> merge this PR :)

+1

With respect to publishing submodule updates (which I don't think you
need to do, since I think you should just merge Erik's PR), they work
like this:
1. Make the new commit in a branch (e.g. `master`) in your submodule
   (your step 1).
2. Push your submodule commit to the public repository that everyone
   else is using (e.g. swcarpentry/lessons_4_0.git), otherwise we
   won't be able to check out your updated version.
3. Commit the changed submodule SHA-1 to your superproject.  In your
   case:
   
    $ git add 4_0
    $ git commit -m '4_0: updated pageclass yada yada…'
4. Push your updated superproject to someplace public (while step 2
   should push to the central swcarpentry repository for the
   submodule, here you can push to your personal gvwilson repository
   for the superproject).

Submodules are basically instructions telling Git, “clone
'submodule.<name>.url' into <gitlink-dirname> and checkout commit
<gitlinked-SHA-1>”.  That means that you need to update and publish
the gitlink in the superproject, and you need to also publish (to the
repository referenced by the URL stored in the superproject's
`.gitmodules`) the submodule commit referenced by the gitlink.

**Comment by embray** [comment]
@wking I don't think this is your fault, but that was utterly incomprehensible :confounded: :gun:

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 07:45:54AM -0800, Erik Bray wrote:

> @wking I don't think this is your fault, but that was utterly
> incomprehensible :confounded: :gun:

Sorry, lemme try with more examples.  Submodules are stored as
gitlinks to a given commit:

  $ git ls-tree HEAD -- 4_0
  160000 commit 6f1748accf39ac2b1526b18b69159be5cb545608  4_0
  $ cd 4_0
  4_0$ git log --oneline
  6f1748a Merge pull request #1 from gvwilson/master

That commit is published in a public submodule repository:

  4_0$ git remote -v
  origin  https://github.com/swcarpentry/lessons_4_0.git (fetch)
  origin  https://github.com/swcarpentry/lessons_4_0.git (push)

which was originally setup from the superproject's `.gitmodules` when
you initialized the submodule:

  4_0$ cd ..
  $ git config submodule.4_0.url    # setup by `git submodule init …`
  https://github.com/swcarpentry/lessons_4_0.git
  $ cat .gitmodules 
  [submodule "4_0"]
          path = 4_0
          url = https://github.com/swcarpentry/lessons_4_0.git
  [submodule "3_0"]
          path = 3_0
          url = https://github.com/swcarpentry/lessons_3_0.git

When you add a commit to your submodule:

  $ cd 4_0
  4_0$ git checkout master
  4_0$ git rm index.html
  4_0$ git commit -m 'no more index, muahaha'
  [master d98c7d5] no more index, muahaha
   1 file changed, 52 deletions(-)
   delete mode 100644 index.html
  4_0$ cd

The superproject notices that the subproject has been updated from the
old commit (6f1748a) to the new commit (d98c7d5):

  $ git status
  …
  #  modified:   4_0 (new commits)
  …
  $ git diff
  diff --git a/4_0 b/4_0
  index 6f1748a..d98c7d5 160000
  --- a/4_0
  +++ b/4_0
  @@ -1 +1 @@
  -Subproject commit 6f1748accf39ac2b1526b18b69159be5cb545608
  +Subproject commit d98c7d5c0751388838de8c547da44f0f48c7667d

This reference (“Subproject commit …”) is called a gitlink, because it
links that Git tree entry (4_0) to another Git commit (6f1748a or
d98c7d5).  You can commit the updated gitlink just like you'd commit a
file:

  $ git add 4_0
  $ git commit -m '4_0: Point to index-less version'

Now you've updated both your local submodule and superproject.  For
other folks to be able to get your updates, you need to publish both
the submodule and superproject changes.  You can push the superproject
changes wherever you want.  If you expect other folks to find them,
the submodule changes have to go to the repository you suggested they
use in the superproject's `.gitmodules`.

As a remote user, when I checkout your superproject changes, I see
that the gitlink has changed:

  $ git checkout origin/master
  $ git status
  …
  #  modified:   4_0 (new commits)
  …

So I update to point to the new commit:

  $ git submodule update

This will try and fetch the new commit (d98c7d5) from my submodule's
upstream repository (https://github.com/swcarpentry/lessons_4_0.git)
so it had better be there (e.g. don't just publish the superproject
update without also publishing the subproject commit the new
superproject commit references).  Once the new commit is fetched, the
update command proceeds to check it out into the `4_0/` directory.

**Comment by jiffyclub** [comment]
I think you can leave the submodule on master. Go back up to website and `git add 4_0` + `git commit -m "Updating submodule reference to latest."`. Whether you do that on master or pageclass depends on whether you want to push straight to swcarpentry/website (then commit in master) or go through gvwilson/website and make a PR (then commit in pageclass).

**Comment by embray** [comment]
@wking Thanks, that clarifies things greatly. I know the original comments weren't even intended for me, but I've never really used submodules so it blew my mind a bit ;)

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 08:14:35AM -0800, Matt Davis wrote:

> I think you can leave the submodule on master.

You can definately leave the submodule on master.  Git 1.8.2 supports
a `submodule.<path>.branch` in `.gitmodules` which can help avoid the
headless state entirely
git/git@902f2f4f0a0bcc6c8d63ad4cd6b75b7eb9d65a72.

**Comment by gvwilson** [comment]
https://github.com/swcarpentry/website/pull/321

**Pull request merged**
