### PR TITLE
Post about oslo bootcamp

### PR DESCRIPTION
**Pull request by karinlag**
Note: both Lex and I are authors, but the system only seems to permit one, which is why I set myself as the author.

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Jul 10, 2013 at 08:20:44AM -0700, karinlag wrote:

> - Adding post about the Oslo bootcamp

A few edits:
- You need to add venues/uio (or an expanded form of that) to metadata.json.
- “endwe” → “end we”, but maybe “In the endwe ended up with” → “We
  ended up with”.
- Standardize “the first day” and “the second day” (not “day 2”).
- “feared  lots” → “feared lots” (double space).
- “windows” → “Windows” (or “MS Windows”).  Also “git” → “Git”, “vcs”
  → “VCS”, “python” → “Python”, ….
- “and that I due to this simply” → “and I simply”.
- “dependables” → “dependencies”.
- “peoples problems” → “people's problems”.
- “of total newbies, to” → “from total newbies to”.
- “teach these people, they were” → “teach these people; they were”.
- “they would ready” → “they would be ready”.
- “project organization. etc” → “project organization, etc.”.

**Comment by karinlag** [comment]
I have now made these changes and pushed them to my repo. How do I proceed
from here?

## 

## Karin

karin.lagesen@gmail.com

**Comment by karinlag** [comment]
Thanks!

On Mon, Jul 15, 2013 at 12:30 PM, Greg Wilson notifications@github.comwrote:

> On 2013-07-15 5:42 AM, karinlag wrote:
> 
> > I have now made these changes and pushed them to my repo. How do I
> > proceed
> > from here?
> > Thanks Karin --- I'll merge it into the master copy later this morning.
> 
> Cheers,
> Greg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/pull/644#issuecomment-20961841
> .

## 

## Karin

karin.lagesen@gmail.com

**Pull request merged**
