### PR TITLE
Tidying up changes to compilation script.

### PR DESCRIPTION
**Pull request by gvwilson**
Minor formatting changes.

### CODE REVIEW

**Comment by wking** [comment]
Docstring formatting like:

```
"""iCalendar generator for boot camps.

The format is defined in RFC 5545.
"""
```

follows PEP 257 [1](http://www.python.org/dev/peps/pep-0257/#multi-line-docstrings), while:

```
"""
iCalendar generator for boot camps.
The format is defined in RFC 5545: http://tools.ietf.org/html/rfc5545
"""
```

does not.  Not that it really matters unless your using a
docstring-processing tool like Sphinx, but it will be less surprising
for other contributors if we migrate to PEP 257 style docstrings at
some point.

**Comment by gvwilson** [comment]
I've chosen consistency over PEP 257 for the moment; if you'd like to 
file an issue, we can fix the docstrings some time soon.

**Comment by jiffyclub** [comment]
From PEP 257:

> The summary line may be on the same line as the opening quotes or on the next line.

And I personally much prefer the latter format:

```
"""
iCalendar generator for boot camps.
The format is defined in RFC 5545: http://tools.ietf.org/html/rfc5545
"""
```

**Comment by wking** [comment]
On Thu, Dec 20, 2012 at 07:42:41AM -0800, Matt wrote:

> From PEP 257:
> 
> > The summary line may be on the same line as the opening quotes or on the next line.

I just learned something new :).

> And I personally much prefer the latter format:
> 
> ```
> """
> iCalendar generator for boot camps.
> The format is defined in RFC 5545: http://tools.ietf.org/html/rfc5545
> """
> ```

This is still not legal.  From PEP 257:

> The summary line may be used by automatic indexing tools; it is
> important that it fits on one line and is separated from the rest of
> the docstring by a blank line.

So perhaps we want (eventually):

```
"""
iCalendar generator for boot camps.

The format is defined in RFC 5545: http://tools.ietf.org/html/rfc5545
"""
```

?

**Comment by jiffyclub** [comment]
Hey, I was just copying you. :wink: 

But yes, it is proper protocol to separate the summary line from the rest by an empty line.

**Pull request merged**
