### PR TITLE
Updating instructions for running the Firefox SQLite Manager

### PR DESCRIPTION
**Pull request by ethanwhite**
As described in #184 the instructions for running SQLite Manager were out of date.

### CODE REVIEW

**Comment by wking** [comment]
I'd remove “on Ubuntu” and just list the alternative location.  This
is probably just a difference between Firefox versions.  I certainly
can't think of a reason why only Ubuntu would patch Firefox to change
this location.

**Comment by ethanwhite** [comment]
It's not a version difference (I'm running 17 on both Windows 7 and Ubuntu), but it does turn out to be possible to have the alternative form on other operating systems, it's just that the default is one way on Ubuntu (related to the integration with Unity's universal menu bar and HUD) and the other way on everything else I've seen. So, yes, we should change it.

**Comment by ethanwhite** [comment]
Done. Is the a preference for amending vs. rebasing for this sort of simple change?

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 12:00:58PM -0800, Ethan White wrote:

> Is the a preference for amending vs. rebasing for this sort of
> simple change?

What's the difference?  I think the Ubuntu reference should be
squashed out (which it looks like you did).  You can do that with an
amend or with a second commit followed by a squash rebase.  The result
is the same (but the amend is easier to do in this case).

On an unrelated note (possibly for another PR?), do we want to use
`=&gt;` here instead of the more semantic (but possibly less well
supported?) `→` (a.k.a '&#x2192;', Unicode's RIGHTWARDS ARROW).

**Comment by ethanwhite** [comment]
OK, so they're the same. That answers my question. Thanks.

The `=&gt;` things seems like something separate, on which I have no opinion.

**Comment by gvwilson** [comment]
I'm in favor of &rarr; instead of =&gt;
- G

**Comment by ethanwhite** [comment]
I'm happy to make the change here if that's appropriate or we can do it in a separate PR. Just let me know.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 12:41:35PM -0800, Ethan White wrote:

> I'm happy to make the change here if that's appropriate or we can do
> it in a separate PR. Just let me know.

I'll open a separate PR.  `git grep` turns up quite about 36 of these
;).

**Pull request merged**
