### PR TITLE
Added reference to Duke camp on NESCent page and vice versa; changed University of North Carolina to NESCent

### PR DESCRIPTION
**Pull request by amyrhoda**

### CODE REVIEW

**Comment by gvwilson** [comment]
Whoops --- d231246 changed the name of the UNC file to '2013-05-nescent.html', so there's a conflict.

**Comment by amyrhoda** [comment]
Um, I don't know what to do now.

**Comment by gvwilson** [comment]
1. Go into your laptop's copy of 'website'.
2. Make sure you're in the branch you were in when you made this edit.
3. Make sure swcarpentry/website is 'upstream'.  (You can check with 'git remote -v'.)
4. 'git pull upstream master'. There will be merge conflicts.  I _think_ you will need to:
   a) edit 2013-05-duke.html to remove the >>> === <<< markers.
   b) 'git rm 2013-05-unc.html'.
   c) edit 2013-05-nescent.html to insert the link to 2013-05-duke.html (basically, recreate what you did to 2013-05-unc.html).
5. 'git add 2013-05-duke.html 2013-05-nescent.html'
6. 'git commit -m "Merging blah blah blah"'
7. 'git push origin branch-name' (where 'branch-name' is whatever branch you used for the initial pull request)
   At that point, the pull request is automagically updated on GitHub.
   Does this make sense?

**Comment by amyrhoda** [comment]
Magic.

**Pull request merged**
