### PR TITLE
Adding four more people to about/team.html

### PR DESCRIPTION
**Pull request by gvwilson**
Adding:
- Ian Langmore
- Emily Jane McTavish
- Lex Nederbragt
- Ariel Rokem

and removing the link index at the bottom of the page as redundant.

### CODE REVIEW

**Comment by jiffyclub** [comment]
As in #341 this has a lot of unnecessary stuff along with it. You can use an interactive rebase (`git rebase -i 6c7cafa`) to easily remove the irrelevant commits.

**Comment by gvwilson** [comment]
Rebased.

**Comment by jiffyclub** [comment]
Is the deletion of the Index section intentional?

**Comment by jiffyclub** [comment]
(Rebase looks great, by the way.)

**Comment by jiffyclub** [comment]
Alright then, looks good.

**Pull request merged**
