### PR TITLE
Convert badges over to using the Javascript Issuer API (Fixes #361)

### LINKED ISSUE #361: Badge URLs don't work
I was looking at my [super-duper SWC badge](http://beta.openbadges.org/share/a77a56b78294f0c174774c00fc37f5a5/) and the URLs associated with it have issues. The "Criteria" URL just goes to a list of created badges, and the "Evidence" link doesn't work at all.

### PR DESCRIPTION
**Pull request by pipitone**
- download links now call the OpenBadges Javascript Issuer API to issue the badge
- significant updates bin/badge.py to only produce JSON assertions
- email addresses are now hashed in assertions
- deleted the badge images and added assertions with salted emails.

### CODE REVIEW

**Comment by pipitone** [comment]
I'm mentioning #361 here to create a link to the issue.

**Comment by pipitone** [comment]
I've just modified this PR significantly.  Could someone have a look and give me comments? 

I've merged all of the individual badge pages into a single page: 
Screenshot from 2013-03-18 17:16:09

Additionally, now when you click on a name, a dialog box shows the underlying badge assertion (as requested by Greg) and lets you add it to your mozilla Backpack: 
Screenshot from 2013-03-18 17:18:20

(This is the use of the [Javascript Issuer API](https://github.com/mozilla/openbadges/wiki/Issuer-API) rather than pre-baking images.)

**Comment by ethanwhite** [comment]
The end result looks awesome, so a big +1. I don't feel qualified to assess what's going on in the background.

**Comment by pipitone** [comment]
Thanks!  It's good to know that looks okay.

**Comment by jiffyclub** [comment]
Why the switch from version 5.0 to 0.5.0 in the badges?

**Comment by pipitone** [comment]
... because that's what it says here:
https://github.com/mozilla/openbadges/wiki/Assertions

version: The version of the spec this manifest is compatible with. Use

> "0.5.0" for the beta.

 That's the only place I saw a directive for a specific version number.
The docs are a bit... impoverished.

Jon.

**Comment by pipitone** [comment]
I can haz merge now?

**Pull request merged**
