### PR TITLE
Adding a 'staffing' page.

### PR DESCRIPTION
**Pull request by gvwilson**
1. Added 'bootcamps/staffing.html' to show who's teaching when and where. (Page is generated automatically from a database in an external repo.)
2. Added links to the page from the pulldown menu and bootcamps/index.html.
3. Added reference to the page to trigger compilation.

### CODE REVIEW

**Comment by wking** [comment]
You can just push (possibly with `--force`) to your branch on gvwilson
to update a pull request.  By creating a new pull request for each
revision, the discussion gets strung out (#334, #330).

**Comment by wking** [comment]
In fact, both this PR and #334 seem to have the same tip (94c6663) ;).

**Comment by wking** [comment]
On Mon, Mar 04, 2013 at 05:35:16AM -0800, Greg Wilson wrote:

> On 2013-03-04 8:27 AM, W. Trevor King wrote:
> 
> > You can just push (possibly with `--force`) to your branch on gvwilson
> > to update a pull request. By creating a new pull request for each
> > revision, the discussion gets strung out (#334, #330).
> > Right, so a pull request isn't "please accept the state of this 
> > repo/branch as it was when I made the request" but "please accept the 
> > _current_ state of this repo/branch"?

That's how GitHub uses them.

Git's `request-pull` command does include the tip SHA in it's message
for additional verification
(git/git@cf7316663e2ae459591bc52f0a1c91c3a684e48b).

**Comment by wking** [comment]
On Mon, Mar 04, 2013 at 05:57:27AM -0800, Greg Wilson wrote:

> Can you please merge this puppy (somehow) and I'll try to do better
> next time?

You can just run something like:

  $ git checkout -b staffing-page master  # put your stuff on a feature branch
  $ git checkout master
  $ git reset --hard origin/master        # point your master at the current tip
  $ git merge staffing-page
  …resolve a single indentation conflict…
  $ git push origin master

GitHub will close the PR automatically when it notices that the PR's
tip commit (94c6663) is in the target branch (swcarpentry:master).

**Comment by jiffyclub** [comment]
I will just figure something out this time and let it be a lesson to @gvwilson to start really seriously thinking about taking my advice about branches. :stuck_out_tongue_winking_eye:

**Comment by jiffyclub** [comment]
I've opened number #337 with a commit of these changes that can be cleanly merged.

**Comment by gvwilson** [comment]
Superseded by cluefulness.

**Pull request closed without merging**
