### PR TITLE
Updating embedded calendar to follow http://software-carpentry.org/bootcamps.ics

### PR DESCRIPTION
**Pull request by jiffyclub**
I made a Google calendar on the admin account that follows our generated calendar file and switched the embedded calendar to point to that. I also added some margin space to the bottom of the map div to put some room between the map and calendar.

### CODE REVIEW

**Comment by wking** [comment]
The patch looks good to me, but I haven't built and tested it.

**Comment by gvwilson** [comment]
If it builds and works for @jiffyclub, please merge it.
- G

**Comment by gvwilson** [comment]
Builds and works for me; only thought is that the calendar title is the URL of the .ics file as plain text (see screenshot): can it either be removed (context makes calendar purpose clear) or changed to be a hyperlink wrapped around the URL?

Screen Shot 2012-12-30 at 7 48 40 PM

**Comment by jiffyclub** [comment]
I just figured out it is possible to set the title to something else (though not sure about a hyperlink), but I just took it off since it probably is superfluous. I also took off the print icon and little pull down button on the far right so it looks like this:

Screen Shot 2012-12-30 at 8 03 19 PM

**Comment by wking** [comment]
You might want to hold off on the s-o-bs until we close #8 [1](https://github.com/swcarpentry/website/issues/8), it's
looking like we may not want them at all.

**Comment by jiffyclub** [comment]
Could do something like this:

Screen Shot 2012-12-30 at 9 28 54 PM

**Comment by jiffyclub** [comment]
Done.

**Comment by wking** [comment]
Looking at 65b6dcfb75, I think we should stick to `label` instead of
adding `swc-label`.  This is why CSS is “cascading”, right?

**Comment by jiffyclub** [comment]
I don't want to actually change the style of `label`, though. That could have other uses. It might be more appropriate to rename `swc-label` to `swc-background` since all it's modifying is the background color.

**Comment by wking** [comment]
On Tue, Jan 01, 2013 at 07:37:22AM -0800, Matt wrote:

> I don't want to actually change the style of `label`, though. That
> could have other uses.

Such as what?  If you want some labels to have a dark background
color, then you probably want all the labels to have the dark
background color.  If you only want some labels to have a dark
background color (e.g. in the footer), you can mask by div ID (as was
done before 65b6dcfb).

If you want to make things “SWC Blue” without forcing a semantic
interpretation, I'd be fine with a `swc-blue` class, but claiming that
some labels are “SWC labels” while others are not smells funny.

**Comment by jiffyclub** [comment]
There are a whole suite of label styles built into Bootstrap, I'm not going to override them: http://twitter.github.com/bootstrap/components.html#labels-badges

I will change the class name to something more informative, though.

**Comment by wking** [comment]
On Tue, Jan 01, 2013 at 08:14:10AM -0800, Matt wrote:

> There are a whole suite of label styles built into Bootstrap, I'm
> not going to override them:
> http://twitter.github.com/bootstrap/components.html#labels-badges

Ah, thanks for the link.  Do we use these labels anywhere?  I don't
see why the default label shouldn't have a blue background.

**Comment by jiffyclub** [comment]
No, I don't think they're in use anywhere else on the site. I just don't want to change defaults and confuse people later. If anyone wants to make a matching label they should be able to copy the existing examples.

**Comment by wking** [comment]
On Tue, Jan 01, 2013 at 08:43:02AM -0800, Matt wrote:

> No, I don't think they're in use anywhere else on the site. I just
> don't want to change defaults and confuse people later. If anyone
> wants to make a matching label they should be able to copy the
> existing examples.

I expect future devs are more likely to not care what color label they
have, and defaulting to SWC branding seems like a good idea.  However,
I don't care enough to argue it further ;).

**Comment by jiffyclub** [comment]
Okay, I amended the last commit so there's now an `swc-blue-bg` class instead of `swc-label`, and updated the current label instances to have that class.

**Comment by jiffyclub** [comment]
I think this is settled enough to merge, I'll hit the button.

**Pull request merged**
