### PR TITLE
Added check-bare to the Makefile for doing an unvalidated build

### PR DESCRIPTION
**Pull request by pipitone**
The reason I'm adding this option is because whilst adding features to the website, I often go through iterations of adding content and rebuild to check that the website looks okay. I find myself always stopping make when it gets to the validation step because early on I just don't care if it's valid or not (it probably is, and if not, I'll fix it up later once the site looks as it should).

### CODE REVIEW

**Comment by jiffyclub** [comment]
Oh thank god, running the build script takes way too damn long.

**Comment by pipitone** [comment]
Another way to speed things up might be to get the makefile to work under parallelisation (i.e. with the -J flag).  Make can do this when a target has multiple dependencies, and we could also use gnu parallel to do some of the work for targets that process bunches of files (I'm looking at you `make check-links`)

**Pull request merged**
